/// Flutter icons KhanaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KhanaIcons
///      fonts:
///       - asset: fonts/KhanaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KhanaIcons {
  KhanaIcons._();

  static const _kFontFam = 'KhanaIcons';
  static const _kFontPkg = null;

  static const IconData analisis = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showitem = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showList = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
