name: khana_mobile_application
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  fluttertoast: ^7.1.1
  # assets libraries
  percent_indicator: "^2.1.7+2"
  flutter_svg: ^0.19.1
  # Icons
  flutter_icons:
  # Provider
  provider:
  # Firebase
  firebase_core: "0.5.0+1"
  firebase_auth:
  cloud_firestore:
  # Localization
  permission_handler: ^5.0.1
  image_picker: ^0.6.6+5
  hive: ^1.4.3
  path_provider: ^1.6.5
  get: ^3.4.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KhanaIcons
      fonts:
        - asset: assets/fonts/KhanaIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
